cart/urls.py
from django.conf.urls.defaults import patterns, url


urlpatterns = patterns('cart.views',
    url(r'^$', 'show_cart', {'template_name':'cart/cart.html'}, name='show_cart'),
)

tradenplay/urls.py
"""
main url configuration file for the site
"""
from django.conf import settings
from django.conf.urls.defaults import handler404
from django.conf.urls.defaults import handler500
from django.conf.urls.defaults import include
from django.conf.urls.defaults import patterns
from django.conf.urls.defaults import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

if getattr(settings, 'ASKBOT_MULTILINGUAL', False) == True:
    from django.conf.urls.i18n import i18n_patterns
    urlpatterns = i18n_patterns('',
                               (r'%s' %
                                settings.ASKBOT_URL, include('askbot.urls'))
                                )
else:
    urlpatterns = patterns('',
                          (r'%s' % settings.ASKBOT_URL, include('askbot.urls'))
                           )

urlpatterns += patterns('',
    (r'^admin/', include(admin.site.urls)),
    # (r'^cache/', include('keyedcache.urls')), - broken views disable for now
    url(r'^catalog/', include('catalog.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^checkout/', include('checkout.urls')),
    (r'^settings/', include('askbot.deps.livesettings.urls')),
    (r'^followit/', include('followit.urls')),
    (r'^tinymce/', include('tinymce.urls')),
    (r'^robots.txt$', include('robots.urls')),
    url(  # TODO: replace with django.conf.urls.static ?
        r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:],
        'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT.replace('\\', '/')},
    ),
    url(r'^accounts/', include('accounts.urls')),
    #url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^search/', include('search.urls')),
    url(r'', include('marketing.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            url(r'^rosetta/', include('rosetta.urls')),
                            )

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler500 = 'utils.views.view_500'
handler404 = 'utils.views.view_404'

cart/models.py
from django.db import models
import datetime 
#from catalog.models import Product

class CartItem(models.Model):
    cart_id = models.CharField(max_length=50)
    date_added = models.DateTimeField(default=datetime.datetime.now)
    quantity = models.IntegerField(default=1)
    product = models.ForeignKey('catalog.Product', unique=False)
    
    class Meta:
        db_table = 'cart_items'
        ordering = ['date_added']
        
    def total(self):
        return self.quantity*self.product.price
    
    def name(self):
        return self.product.name
    
    def price(self):
        return self.product.price
    
    def get_absolute_url(self):
        return self.product.get_absolute_url()
    
    def augment_quantity(self, quantity):
        self.quantity += int(quantity)
        self.save()

search/models.py
from django.db import models
from django.contrib.auth.models import User


class SearchTerm(models.Model):
    q = models.CharField(max_length=50)
    search_date = models.DateTimeField(auto_now_add=True)
    ip_address = models.IPAddressField()
    user = models.ForeignKey(User, null=True)
    tracking_id = models.CharField(
        max_length=50, default='', blank=True, null=True)

    def __unicode__(self):
        return self.q

catalog/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from tagging.models import Tag

from .models import Product, ProductReview


class ProductAdminForm(forms.ModelForm):

    """
    ModelForm class to validate product instance
    data before saving from admin interface
    """
    class Meta:
        model = Product

    def clean_price(self):
        if self.cleaned_data['price'] <= 0:
            raise forms.ValidationError(
                _('Price supplied must be greater than zero.'))
        return self.cleaned_data['price']


class ProductAddToCartForm(forms.Form):

    """
    form class to add items to the shopping cart
    """
    quantity = forms.IntegerField(
        widget=forms.TextInput(
            attrs={
                'size': '2',
                'value': '1',
                'class': 'quantity'
            }
        ),
        error_messages={
            'invalid': _('Please enter a valid quantity.')},
        min_value=1)

    slug = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, request=None, *args, **kwargs):
        """ override the default so we can set the request """
        self.request = request
        super(ProductAddToCartForm, self).__init__(*args, **kwargs)

    def clean(self):
        """
        custom validation to check for
        presence of cookies in customer's browser
        """
        if self.request:
            if not self.request.session.test_cookie_worked():
                raise forms.ValidationError(_("Cookies must be enabled."))
        return self.cleaned_data


class ProductReviewForm(forms.ModelForm):

    class Meta:
        model = ProductReview
        exclude = ('user', 'product', 'is_approved', 'date')


class TagForm(forms.ModelForm):

    class Meta:
        model = Tag

templates/tags/cart_box.html
{# Usage: "cart_box request" #}
{% load i18n %}
{% load static %}
{% with cart_item_count as cart_count %}
<a href="{% url show_cart %}">
    <!-- <i class="icon-shopping-cart icon-white"> </i> -->
    <ul class="inline pull-right span1">
    	<li><img class="menu_cart_icon"src="{% get_static_prefix %}img/cart_big_white.png" alt="" /></li>
    	<li><p class="font_19px">{{ cart_count }} </p></li>
    </ul>
    
    
<a/>
{% endwith %}



templates/tags/category_list.html
{% load i18n %}



<a href="" class="dropdown-toggle" data-toggle="dropdown">
    {% trans "Categories" %} 
    <b class="caret"></b>
</a>
<ul class="dropdown-menu">
{% with category_structure_list as struct_list %}
    
    {% for item in struct_list %}
        {% if item.action == "open_nested_menu" %}
           
            <li class="dropdown-submenu">
                <a href="{% url catalog_category slug=item.object.slug %}" tabindex="-1">  
                {{ item.object.name }}
                </a>           
                 <ul class="dropdown-menu">   
            
        {% elif item.action == "close_nested_menu" %}
                </ul>    
            </li>
        
        {% else %}
            <li class="">
                {% ifequal item.object.get_absolute_url request_path %}
                    {{ item.object.name }}
                {% else %}
                    <a href="{% url catalog_category slug=item.object.slug %}" tabindex="-1">
                        {{ item.object.name }}
                    </a>
                {% endifequal %}
            </li>
            
        {% endif %}
    {% endfor %}
{% endwith %}   
</ul>

templates/tags/footer.html
{% load i18n %}
<a href="{% url catalog_home %}"> {% trans "Home" %}</a>
{% with flatpage_list as pages %}
    {% for page in pages %}
        <a href="{{ page.url }}">{{ page.title }}</a>
    {% endfor %}
{% endwith %}

templates/tags/form_table_row.html
<tr>
    <th>
        {% if form_field.field.required %}*{% endif %}
        {{ form_field.label_tag }}
    </th>
    <td>
    {% if form_field.errors %}
        <ul class="errorlist">
        {% for error in form.field_errors %}
            <li> {{ form_field.label }}: {{ error }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    
    {{ form_field }}
    </td>
</tr>

templates/tags/invite_to_login.html
{% load i18n %}
{% if not request.user.is_authenticated %}
    <div class="fr">
        <a href="{% url accounts_log_in %}?next={{request.path}}">
            {% trans "Already have an account?" %}<br />
            {% trans "Sign in now!" %}
        </a>
    </div>
{% endif %}

templates/tags/navigation.html
{% load i18n %}
<div class="inline">
	<ul class="inline">
		<li><a href="{% url catalog_home %}">Home</a></li>
		<li><a href="/about/">About</a></li>
		<li><a href="/privacy-policy/">Privacy</a></li>
		<li><a href="/contact/">Contact</a></li>
		
		{% if user.is_authenticated %}
            <li>
                <a href="{% url my_account %}">{% trans "My Account" %}</a>
            </li>
        {% endif %}
	    
	    
	
		<div class="pull-right auth_box_wrapper">
			<div id="auth_box">
	   			 {% include "registration/auth_box.html" %}
			</div>
			<div class="cb"></div>
		</div>
	</ul>
</div>

templates/tags/pagination_links.html
{% load i18n %}
{% if p.has_other_pages %}
    {% if  p.has_previous %}
        <a href="{{ request.path}}?{{ params }}&page={{ p.previous_page_number }}">
            &laquo; {% trans "Previous" %}
        </a>
    {% else %}
        &laquo; {% trans "Previous" %}
    {% endif %}
    | Page {{ p.number }} {% trans "of" %} {{ paginator.num_pages }} |
    {% if p.has_next %}
        <a href="{{ request.path }}?{{params}}&page={{ p.next_page_number }}">
            {% trans "Next" %} &raquio;
        </a>
    {% else %}
        {% trans "Next" %} &raquio;
    {% endif %}
{% endif %}

templates/tags/product_list.html
{% load i18n %} 

{% for product in products %}
{% if forloop.first %}
<h4> {{ header_text }}</h4>
{% endif %}
<div class="product_thumbnail_wrapper thumbnail span2" data-product-id="{{ product.id }}">
    
    {% include 'tags/product_thumbnail.html' %}
    <div class="price_n_actions">
        <ul class="inline pull-right">
            <li><h5 class="text-info">{% trans "Price:" %}</h5></li>
            <li><h4 class="text-success">{{ product.price }}</h4></li>
        </ul>
        <br />
        <div class="span1 pull-right">
            
            <div class="to-cart">
                <form method="post" action="{% url catalog_product slug=product.slug %}" class="form-inline ">
                    
                    <input name="quantity" id="id_quantity"  class="quantity form-control input-mini" type="hidden" value="1">
                    <input class="add_to_cart_input" type="hidden" name="slug" value="{{ product.slug }}" id="id_slug">
                    <button  class="btn btn-info btn-large add_to_cart_input "type="submit">
                        <i class="icon-plus"></i>&nbsp;
                        <i class="icon-shopping-cart"></i>
                        &nbsp;
                    </button>
                    
                </form>
            </div>
        </div>
    </div>
    <br />
    <div class="ellipsis">{{ product.description|truncatechars:100 }}</div>
    
</div>
{% if forloop.last %}

{% endif %}
{% endfor %}



templates/tags/product_thumbnail.html
<div class="product_thumbnail">
	<a class="" href="{% url catalog_product slug=product.slug %}">
		{% if product.thumbnail_url %}
			<img class=" " src="{{ product.thumbnail_url }}" alt="{{ product.name }}"  />
			<br />
		{% else %}
			<img class="" src="{{ product.image_url }}" alt="{{ product.name }}"  />
			<br />
		{% endif %}
		<h5>{{ product.name }}</h5>
        
	</a>
</div>

templates/tags/search_box.html
{% load i18n %}
<script>
    $(document).ready(
        function(){
            $( "input#id_q" ).autocomplete({
                    source: "{% url catalog_autocomplete_products %}",
                    minLength: 2
            });
        }
    );
</script>

<form id="search" class="navbar-search" action="{% url search_results %}" method="get">
    <div >
        <input type="text" placeholder="Search" class="search-query" id="id_q"/>
    </div>
</form>
